import javax.swing.JFrame;
import javax.swing.JButton;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public int i = 0;
    private JFrame frame;

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
    }

    public App() {
        frame = new JFrame("Test Window");
        frame.setSize(400,400);

	JButton b = new JButton("test");
        b.addActionListener( e -> {
            this.i = 2;
            System.out.println(i);
        });
        frame.add(b);
        frame.setVisible(true);
    }

    public int add(int a, int b) {
        return a + b;
    }

    public void close() {
        frame.setVisible(false);
        frame.dispose();
    }
}
